workflows:
  android-debug:
    name: Android Debug APK
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Generate launcher icon
        script: |
          dart run flutter_launcher_icons
      - name: Analyze
        script: |
          flutter analyze --no-fatal-infos --no-fatal-warnings
      - name: Build debug APK
        script: |
          flutter build apk --debug --flavor stable
    artifacts:
      - build/app/outputs/flutter-apk/app-stable-debug.apk
