class AnsarConfig {
  static const supabaseUrl = 'https://dktukfkitlfwpporhjsm.supabase.co';
  static const supabaseAnonKey =
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrdHVrZmtpdGxmd3Bwb3JoanNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTY5MzUsImV4cCI6MjA2MzQzMjkzNX0.PNSUNkWMK2iSBQxTcv2yYyW7LvouWMKS914yMfdvhXE';
  static const supabaseServiceKey =
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrdHVrZmtpdGxmd3Bwb3JoanNtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0Nzg1NjkzNSwiZXhwIjoyMDYzNDMyOTM1fQ.KXAxyAoADWgJHXD7EIr_X3grp3dTyGzR80MQ3VuLs7Y';
}
